### PR TITLE
Adding preconditions and unknown tables

### PR DESCRIPTION
**Pull request by ulisespulido**
Adding preconditions and unknown tables based on input from issue #6

### CODE REVIEW

**Comment by ulisespulido** [comment]
@solojavier Please review whenever is possible.

**Comment by solojavier** [comment]
Tagging like a pro :)

Looks good

Are you planning to add support for AND and BUT later? or is that something not worth the effort?

**Comment by ulisespulido** [comment]
@solojavier AND and BUT are currently supported, they fall under the Unknown category among all other annotations that are not GIVEN, THEN or WHEN.

Thanks

**Comment by solojavier** [comment]
Yes I was not clear. I mean classifying AND or BUT either as precondition or action depending on what keyword is before them...

**Comment by ulisespulido** [comment]
Yeah, well I don't think you can do that, at least not with this implementation that only takes into consideration the step annotation name not its order in the feature file...

**Comment by solojavier** [comment]
Got it, thanks. No further questions or comments.

**Pull request merged**
